---
- src: https://github.com/resmo/ansible-role-ntp
  path: roles
  version: 0.4.0

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-install
  path: roles

# called -2 because it replaces another role called ansible-role-yum-cron
- src: https://github.com/jeffwidman/ansible-yum-cron
  path: roles
  name: ansible-role-yum-cron-2
  version: 9d587da913eaa82349e86b4fb9d691818538963b

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-users
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-rsyslog
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-dhcp_server
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_bootstrap
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-squid
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-ferm-firewall
  path: roles
  name: ansible-role-ferm-firewall

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-fail2ban
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-slurm
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-cvmfs
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-aliases
  path: roles
  name: ansible-role-aliases

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-rdma
  path: roles

- src: https://github.com/willshersystems/ansible-sshd
  path: roles
  name: ansible-role-sshd
  version: b3df4fae54bd4ff36cc45ecf6dad43da06d353bb

- src: https://github.com/CSC-IT-Center-for-Science/ansible-system-limits
  path: roles
  name: ansible-role-system-limits

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-arc-client
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-yum
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-flowdock
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-collectd
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-pxe_config
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-dnsmasq
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-nis
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-nfs
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-nfs_mount
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-arc-frontend
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-bash
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-cuda
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-nhc
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-dell
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-sshd-host-keys
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-smartd
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-postfix
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-repo
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-login
  path: roles

- src: https://github.com/mhakala/ansible-role-adauth
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-pdsh-machines
  path: roles
